webcrdf/appcbir/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from appcbir import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'djcbir.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

##    url(r'^admin/',   include(admin.site.urls)),
##    url(r'^login/',   views.Login,  name='Login'),
##    url(r'^logout/',  views.Logout, name='Logout'),
    url(r'^$',              views.Index,            name='index'),
    url(r'^upload/',        views.Upload,           name='upload'),
    url(r'^clean/',         views.cleanUplodedData, name='clean'),
    url(r'^api/dbinfo/',    views.apiRequestDbInfo, name='apiRequestDbInfo'),
    url(r'^api/searchdb/',  views.apiSearchDB,      name='apiSearchDB'),

)

webcrdf/appsegmct/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

##from test_sessions import views
from appsegmct import views

urlpatterns = patterns('',
    url(r'^$',          views.Index,			    name='index'),
    url(r'^upload/',    views.Upload,			    name='upload'),
    url(r'^uploadfdb/', views.UploadFromDB,		    name='uploadfdb'),
    url(r'^clean/',     views.cleanUplodedData,     name='clean'),
    url(r'^getinfo/',   views.getInfoAboutImages,   name='getinfo'),
    url(r'^gallery/',   views.ImageGallery,         name='gallery'),
)

webcrdf/appxray/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

##from test_sessions import views
from appxray import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'test_sessions.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

##    url(r'^admin/', include(admin.site.urls)),
    url(r'^$',          views.Index,			name='index'),
    url(r'^upload/',    views.Upload,			name='upload'),
    url(r'^uploadfdb/', views.UploadFromDB,		name='uploadfdb'),
    url(r'^clean/',     views.cleanUplodedData, name='clean'),
    url(r'^roisearch/', views.ROISearch,		name='roisearch'),
    url(r'^gallery/',	views.ImageGallery,		name='gallery'),
)

webcrdf/webcrdf/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from webcrdf import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'webcrdf.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

##    url(r'^admin/', 	include(admin.site.urls)),
    url(r'^$',		views.Index,  name='main-home'),
    url(r'^login/',	views.Login,  name='main-login'),
    url(r'^logout/',	views.Logout, name='main-logout'),
    # url(r'^showct/',	views.ShowCT, name='main-showct'),
    url(r'^appwebcam/',	views.WebCamSearch, name='main-webcam'),
    url(r'^camelyon2016/', views.Camelyon2016, name='main-camelyon'),
    url(r'^dataset-tb5classes/', views.DatasetTB5Classes, name='main-dataset-tb5classes'),
    url(r'^appcbir/',	include('appcbir.urls',  namespace='appcbir', app_name='appcbir')),
    url(r'^appxray/',	include('appxray.urls',  namespace='appxray', app_name='appxray')),
    url(r'^appsegmxr/',	include('appsegmxr.urls',  namespace='appsegmxr', app_name='appsegmxr')),
    url(r'^appmelanoma/',	include('appmelanoma.urls',  namespace='appmelanoma',   app_name='appmelanoma')),
    url(r'^appsegmct/',		include('appsegmct.urls',    namespace='appsegmct',     app_name='appsegmct')),
    url(r'^appdrugres/',	include('appdrugres.urls',   namespace='appdrugres',    app_name='appdrugres')),
    url(r'^apphistology/',	include('apphistology.urls', namespace='apphistology',  app_name='apphistology')),
    url(r'^appvideocbir/',	include('appvideocbir.urls', namespace='appvideocbir',  app_name='appvideocbir')),
    url(r'^appctslice/',	include('appctslice.urls',   namespace='appctslice',    app_name='appctslice')),
    url(r'^appsegmxrdnn/',	include('appsegmxrdnn.urls',  namespace='appsegmxrdnn', app_name='appsegmxrdnn')),
)

webcrdf/appsegmxrdnn/models.py
from django.db import models

# Create your models here.

webcrdf/appcbir/views.py
from webcrdf.settings import CBIR

__author__ = 'ar'

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse

from django.views.decorators.cache import cache_page

from django.conf import settings
from django.conf.urls.static import static

import cv2
import numpy as np
import os
import glob
import shutil
import json
import time
import math

def Index(request):
    print 'static URL: %s' % settings.STATIC_ROOT_USERDATA_CBIR
    if 'is_logged' in request.session:
        userName = 'Unknown'
        if 'username' in request.session:
            userName = request.session['username']
        uploadedImages=getUploadedImageList(request.session.session_key)
        context={'userName': userName, 'uploadedImages': uploadedImages}
        return render(request, 'appcbir.html', context)
    else:
        # return render(request, 'login.html')
        context={'next': '/appcbir/'}
        # return render(request, 'login.html', context)
        return HttpResponseRedirect('/login/?next=%s' % request.path)

def Login(request):
    print '::Login: session-Id = (%s)' % request.session.session_key
    if not 'is_logged' in request.session:
        request.session['is_logged'] = '1'
        request.session['username'] = 'Anonymous'
    return HttpResponseRedirect(reverse('appcbir:index')) ##('/')

# def LoginHtml(request):
#     return render(request, 'login.html')

def Logout(request):
    print '::Logout: session-Id = (%s)' % request.session.session_key
    if 'is_logged' in request.session:
        del request.session['is_logged']
    if 'username' in request.session:
        del request.session['username']
    return HttpResponseRedirect(reverse('appcbir:index')) ##('/')

################################################
@cache_page(60 * 60)
def apiRequestDbInfo(request):
    #ret=json.dumps((CBIR.dataIdxP.tolist(), CBIR.dataPrvPath, CBIR.dataPrvMean, CBIR.dataImgPath))
    ret=json.dumps((CBIR.dataIdxP.tolist(), CBIR.dataPrvPath, CBIR.dataPrvMean))
    # print ret
    return HttpResponse(ret)

################################################
def postProcSearchResults(res):
    imgUrls=[]
    for ii in res[3]:
        imgUrls.append('%s%s/%s.png' % (settings.STATIC_URL, settings.STATIC_DB_DIR, CBIR.dataImgPath[ii]) )
    return (imgUrls, res[1].tolist(), res[0][0:100,9].tolist(), res[3].tolist(), res[0][0:100,8].tolist())

def apiSearchDB(request):
    print request.POST, " : ", len(request.POST)
    if not 'is_logged' in request.session:
        return HttpResponse(json.dumps(()))
    if request.method=='POST':
        qType=json.loads(request.POST['type'])
        res=None
        if qType:
            qFimg=request.POST['fimg']
            # qFimg=json.loads(request.POST['fimg'])
            fimg = '%s/%s/%s' % (settings.STATIC_ROOT_USERDATA_CBIR, request.session.session_key, qFimg)
            print fimg
            res=CBIR.findNgbh(fimg, numRet=10)
            # res=CBIR.findNgbh2(fimg, numRet=10)
            # res=CBIR.findNgbhV(fimg, numRet=10)
            # return HttpResponse(json.dumps(()))
        else:
            idxImg = int(request.POST['idx'])
            # idxImgPath="%s/%s.png" % (settings.STATIC_ROOT_DATADB, CBIR.dataImgPath[idxImg])
            # print "[%d] : %s" % (idxImg, idxImgPath)
            res=CBIR.findNgbhInDB(idxImg,numRet=10)
            # res=CBIR.findNgbhInDB2(idxImg,numRet=10)
            # res=CBIR.findNgbhInDBV(idxImg,numRet=10)
        ret=postProcSearchResults(res)
        # 0: urls, 1: dist, 2: CT-index, 3: Img-index, 4: Img-Index in CT
        return HttpResponse(json.dumps(ret))
    else:
        return HttpResponse(json.dumps(()))

################################################
class ImageUplInfo:
    def __init__(self, url, size, idx):
        self.url=url
        self.sizeW=size[0]
        self.sizeH=size[1]
        self.idx=idx

def getUploadedImageList(sessionId):
    wdir='%s/%s' % (settings.STATIC_ROOT_USERDATA_CBIR,sessionId)
    lstImg=glob.glob('%s/*' % wdir)
    print lstImg
    ret=[]
    for ii in lstImg:
        if os.path.isfile(ii):
            tfimg=os.path.basename(ii)
            timgInfo = ImageUplInfo('%s/users_cbir/%s/%s' % (settings.STATIC_URL, sessionId, tfimg), (100,100), 'imguser_%s' % tfimg)
            ret.append( timgInfo )
    return ret

################################################
def cleanUplodedData(request):
    if not 'is_logged' in request.session:
        return HttpResponseRedirect('/')
    wdir='%s/%s' % (settings.STATIC_ROOT_USERDATA_CBIR, request.session.session_key)
    if not os.path.isdir(wdir):
        return HttpResponseRedirect(reverse('appcbir:index'))
    shutil.rmtree(wdir)
    return HttpResponseRedirect(reverse('appcbir:index'))


################################################
class UploadFileForm(forms.Form):
    # title = forms.CharField(max_length=50)
    file = forms.FileField()

def Upload(request):
    print '::Upload: session-Id = (%s)' % request.session.session_key
    if not 'is_logged' in request.session:
        return HttpResponseRedirect(reverse('ray:index')) ##('/')
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            odir='%s/%s' % (settings.STATIC_ROOT_USERDATA_CBIR, request.session.session_key)
            handle_uploaded_file(odir, request.FILES['file'])
        return HttpResponseRedirect(reverse('appcbir:index')) ##('/')
    else:
        form = UploadFileForm()
        # return HttpResponseRedirect('/')
    # return render_to_response('upload.html', {'form': form})
    return render_to_response('index.html', {'form': form})

def handle_uploaded_file(odir, f):
    if not os.path.isdir(odir):
        os.mkdir(odir)
    fout='%s/%s' % (odir,f.name)
    print fout
    with open(fout, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)

################################################

webcrdf/apphistology/views.py
# from bzrlib.osutils import isfile
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.conf import settings
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse


import os
import json
from webcrdf.settings import HISTOLOGY
import webcrdf.settings as sett

# Create your views here.
################################################
def Index(request):
    print '(apphistology) static URL: %s' % settings.STATIC_ROOT_SEGMCT_USERDATA
    print 'path: [%s]' % request.path
    if 'is_logged' in request.session:
        userName = 'Unknown'
        if 'username' in request.session:
            userName = request.session['username']
        context={'userName': userName, 'uploadedImages': None}
        return render(request, 'apphistology.html', context)
    else:
        # context={'next': '/apphistology/'}
        # return render(request, 'login.html', context)
        return HttpResponseRedirect('/login/?next=%s' % request.path)

def apiSearch(request):
    print request.POST, " : ", len(request.POST)
    if not 'is_logged' in request.session:
        return HttpResponse(json.dumps(()))
    if request.method=='POST':
        qIdxSlide=int(request.POST['idSlide'])
        qIdxRow=int(request.POST['idRow'])
        qIdxCol=int(request.POST['idCol'])
        if not os.path.isdir(sett.STATIC_ROOT_HISTOLOGY_USERDATA):
            os.mkdir(sett.STATIC_ROOT_HISTOLOGY_USERDATA)
        odir="%s/%s" % (sett.STATIC_ROOT_HISTOLOGY_USERDATA, request.session.session_key)
        print request.POST
        retJSON=HISTOLOGY.processSelection(qIdxSlide, qIdxRow, qIdxCol, odir)
        return HttpResponse(json.dumps(retJSON))
    else:
        return HttpResponse(json.dumps(()))

webcrdf/appvideocbir/views.py
# from bzrlib.osutils import isfile
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.conf import settings


import os
import json
from webcrdf.settings import VIDEOCBIR
import webcrdf.settings as sett

# Create your views here.
################################################
def Index(request):
    # print '(appvideocbir) static URL: %s' % settings.STATIC_ROOT_VIDEOCBIR_USERDATA
    # print 'path: [%s]' % request.path
    if 'is_logged' in request.session:
        userName = 'Unknown'
        if 'username' in request.session:
            userName = request.session['username']
        context={'userName': userName, 'uploadedImages': None}
        return render(request, 'appvideocbir.html', context)
    else:
        return HttpResponseRedirect('/login/?next=%s' % request.path)

def apiSearch(request):
    print request.POST, " : ", len(request.POST)
    if not 'is_logged' in request.session:
        return HttpResponse(json.dumps(()))
    if request.method=='POST':
        qIdxVideo=int(request.POST['idVideo'])
        qIdxFrame=int(request.POST['idFrame'])
        retJSON=VIDEOCBIR.processSelection(qIdxVideo, qIdxFrame)
        # retJSON=[]
        return HttpResponse(json.dumps(retJSON))
    else:
        return HttpResponse(json.dumps(()))

webcrdf/templates/appsegmxr.html
{% extends "base.html" %}
{% block content %}
{#    <link href="/data/cssjs/ekko-lightbox.min.css" type="text/css">#}
{#    <script src="/data/cssjs/ekko-lightbox.min.js" type="text/javascript"></script>#}
    <link href="/data/cssjs/ekko-lightbox.css" type="text/css">
    <script src="/data/cssjs/ekko-lightbox.js" type="text/javascript"></script>
    <style type="text/css">
        .container00 {
            position: relative;
            width: 200px;
            height: 200px;
            display: inline-block;
        }
        .main_image00 {
            width: 100%;
            height: 100%;
        }
        .overlay_image00 {
            position: absolute;
            top: 10px;
            left: 10px;
        }
        .div-90p {
            width: 100%;
        }
        .algnc {
            text-align: center;
        }
    </style>
    <div class="container div-90p">
        <div class="row">
            <div class="col-xs-12 col-sm-4 col-md-4 col-lg-3">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4> <kbd>1</kbd> Upload your X-Ray chest image:</h4>
                    </div>
                    <div class="panel-body">
                        {% block upload %}
                            <form role="form" id="id_form_upload" style="padding: 2px" enctype="multipart/form-data" method="post" action="{% url 'appsegmxr:upload' %}">
                                <div class="btn-group-vertical" style="width: 100%;">
                                    <a href="#" class="btn btn-success btn-block" id="id_showdb" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-th"></span> Select from our Database</a>
                                    <input class="btn btn-primary" type="file" value="file" name="file" id="id_file" />
                                    <a class="btn btn-danger" href="{% url 'appsegmxr:clean' %}"><span class="glyphicon glyphicon-remove-circle"></span> Remove files</a>
                                </div>
                            </form>
                        {% endblock %}
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-8 col-md-8 col-lg-7">
                <div class="panel panel-default">
                    <div class="panel-heading algnc">
                        <h4> <kbd>2</kbd> Segmentation results:</h4>
                    </div>
                    <div class="panel-body algnc">
                        <div id="user_images" style="min-height: 300px;">
                            {% for ii in uploadedImages %}
                                <a id="a_{{ ii.idx }}" class="container00" href="{{ ii.url }}" data-toggle="lightbox" data-title="{{ ii.idx }}" data-footer="{{ ii.sizeW }}x{{ ii.sizeH }}" data-buttona="Download">
                                    <img class="img-thumbnail img-user" alt="100x100" src="{{ ii.url }}" style="width: {{ ii.sizeW }}px; height: {{ ii.sizeH }}px;" id="{{ ii.idx }}">
                                    <i class="overlay_image00 fa fa-refresh fa-inverse fa-spin fa-3x" id="info_{{ ii.idx }}"></i>
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" style="width: 90%; height: 90%">
    <div class="modal-content" style="width: 100%; height: 100%">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">X-Ray database</h4>
      </div>
      <div class="modal-body" style="width: 100%; height: 80%; overflow: scroll;" id="idx_gallery"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" id="gallery-close">Close</button>
      </div>
    </div>
  </div>
</div>

<script type="application/javascript">
    var currentImageInfo = null;
    $(document).delegate('*[data-toggle="lightbox"]', 'click', function(event) {
        event.preventDefault();
        $(this).ekkoLightbox.defaults.onShow = function() {
            console.log("::onShow()");
            $("#lightbox_btna").on("click", function() {
                var urlZip = $("#lightbox_img_href").attr('src');
                //TODO: This IS STUPID HAK(FUCK)!!!!
                urlZip = urlZip.substr(0,urlZip.length-13) + ".zip";
{#                $.fileDownload(urlZip);#}
                window.location=urlZip;
                console.log("::onClick() : " + urlZip);
            });
        };
        return $(this).ekkoLightbox();
    });
    $(function () {
        var timeCounter = 0;
        var timeDelay   = 1000;
        ///////////////////////////////////////
        function imageListUpdater() {
            $.ajax({
                url: "{% url 'appsegmxr:getinfo' %}",
                success: function(data) {
                    currentImageInfo = $.parseJSON(data);
                    console.log(currentImageInfo);
                    var isAllFinished = true;
                    var tStatus, tIdx;
                    for(var ii=0; ii<currentImageInfo.length; ii++) {
                        tStatus = currentImageInfo[ii].isFinished;
                        tIdx    = currentImageInfo[ii].idx;
                        if(tStatus) {
                            $('#'   + tIdx).attr('src', currentImageInfo[ii].urlSegm);
                            $('#a_' + tIdx).attr('href',currentImageInfo[ii].urlSegm);
                            $('#info_' + tIdx).hide();
                        } else {
{#                            $('#'   + tIdx).attr('src', currentImageInfo[ii].url);#}
{#                            $('#a_' + tIdx).attr('href',currentImageInfo[ii].url);#}
                            $('#info_' + tIdx).show();
                            isAllFinished = false;
                        }
                    }
                    if(!isAllFinished) {
                        updateImageList();
                    }
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    console.log("ERROR[Ajax] : status=" + textStatus);
                }
            });
        }
        function updateImageList() {
            var currDelay = 100;
            if(timeCounter>0) {
                currDelay=timeDelay;
            }
            setTimeout(function() {
                console.log("Timeout: " + timeCounter);
                timeCounter++;
                imageListUpdater();
            }, currDelay);
        }
        updateImageList();
        ///////////////////////////////////////
        $("#id_help").tooltip({html:true});
        $("#navbar-segmxr").addClass("active");
        $('.alert .close').on('click', function(e) {
            $(this).parent().hide();
        });

        $("#id_file").on("change", function() {
            $("#id_form_upload").submit();
        });
        var funShowErrorMessage = function(txt) {
            $('#message-error-text').html(txt);
            $('#message-error').show();
        };
    /////////////////////////////////////////////////
        $("#id_showdb").on('click', function () {
            var gal = $('#idx_gallery');
            var param={'num': 10};
            $.ajax({
                url: "{% url 'appsegmxr:gallery' %}",
                type: "POST",
                data: param,
                success: function (data, textStatus, jqXHR) {
                    var tobj = $.parseJSON(data);
                    var dataLen=tobj.length;
                    var maxSiz=200;
                    gal.empty();
                    for(var ii=0; ii<dataLen; ii++) {
                        var tUrl = tobj[ii].url;
                        var pw = 1;
                        var ph = 1;
                        if (tobj[ii].w >= tobj[ii].h) {
                            pw = maxSiz;
                            ph = Math.floor(maxSiz * tobj[ii].h / tobj[ii].w);
                        } else {
                            pw = Math.floor(maxSiz * tobj[ii].w / tobj[ii].h);
                            ph = maxSiz;
                        }
                        var tmpImg = $('<img>',{
                            class: 'img-thumbnail',
                            width:  pw,
                            height: ph,
                            id:  'gal_'+tobj[ii].idx,
                            src: tUrl
                        });
                        $(tmpImg).on('click', function() {
                            var spl = this.src.split('/');
                            var fn  = spl[spl.length-1];
                            console.log(fn);
                            $('#gallery-close').click();
                            var param2={'fname': fn};
                            $.ajax({
                                url: "{% url 'appsegmxr:uploadfdb' %}",
                                type: "POST",
                                data: param2,
                                success: function (data, textStatus, jqXHR) {
                                    console.log(data);
                                    window.location="{% url 'appsegmxr:index' %}";
                                },
                                error: function (jqXHR, textStatus, errorThrown) {
                                    funShowErrorMessage('Server error: bad image in DB');
                                }
                            });
                            //window.location="/";
                        });
                        $(tmpImg).css('cursor','pointer');
                        $(tmpImg).prop('title', 'Press mouse button to add image');
                        gal.append(tmpImg);
                    }
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    funShowErrorMessage('Error gallery query...');
                }
            });
        });
    /////////////////////////////////////////////////
    });
</script>

{% endblock %}

webcrdf/templates/ctview-test.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
	<head>
    	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    	<!-- iOS meta tags -->
    	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"/>
    	<meta name="apple-mobile-web-app-capable" content="yes">
    	<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

    	<link rel="stylesheet" type="text/css" href="/data/cssjs3/papaya.css" />
    	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script type="text/javascript" src="/data/cssjs3/papaya.js"></script>

    	<title>Papaya Viewer</title>

    	<script type="text/javascript">
            var params = [];
            params["images"] = ['{{ urlCT }}'];
        </script>
	</head>

	<body>
		<div class="papaya" data-params="params"></div>
	</body>
</html>

webcrdf/templates/login.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
    <title>Login Form</title>
</head>
<body role="document" style="padding: 8px;">
    <div class="container theme-showcase">
        <div class="jumbotron">
            <h1>Hello, User!</h1>
            <p>Please login for to continue working on our portal...</p>
            {% if next %}
        	<p><a href="/login/?next={{ next }}" class="btn btn-primary btn-lg" role="button">Continue</a></p>
            {% else %}
        	<p><a href="/login/" class="btn btn-primary btn-lg" role="button">Login</a></p>
            {% endif %}
        </div>
    </div>
</body>
</html>